---
layout: resume
title: Brandon Hagerman's Resume
---
# Brandon Hagerman
Computer Science student at BYU-Idaho

<div id="webaddress">
<a href="datascience@byui.edu">datascience@byui.edu</a>
| <a href="https://byuidatascience.github.io/development.html">Data Science Program</a>
</div>

## Education

`Expected 2025`
__Brigham Young University - Idaho__, Rexburg, ID

- 3.8 Major GPA

## Related Experience

### Internships

`May 2023 - August 2023`
__Melaleuca__, Idaho Falls, ID

- Upgraded Content Management System from Vue 2 to Vue 3
- Developed new page to help employees change product details more easily
- Integrated Typescript for type safety and higher quality code base

### Software Engineer

`August 2023 - Present`
__Melaleuca__, Software Engineer I

- Worked with .Net for fixing bugs and creating new business features
- Integrated Google Vision Client to AWS Pipeline for Product Recognition via Images
- Worked with Git, Azure Devops, and Postman

## Service and Work History

`Fall 2022`
Cloud Solution Society Member

`2019-2020`
__Missionary__, Dallas, Texas

<!-- ### Footer

Last updated: May 2013 -->


